"use client";

import axios from "axios";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "react-toastify";
import ErrorState from "@/components/shared/ErrorState";
import LoadingState from "@/components/shared/LoadingState";
import { useDialogAccessibility } from "@/hooks/useDialogAccessibility";
import { normalizeApiError } from "@/lib/api-error";
import { adminService, type AdminPermissionResource } from "@/services/admin/adminService";
import type { AdminRole, AdminRolePayload } from "@/types/identity";
import AdminConfirmDialog from "./AdminConfirmDialog";
import AdminDataTable from "./AdminDataTable";

const systemRoles = new Set(["admin", "customer", "cskh", "marketing", "technical"]);

function RoleDialog({ role, permissions, busy, onClose, onSubmit }: { role: AdminRole | null; permissions: AdminPermissionResource[]; busy: boolean; onClose: () => void; onSubmit: (payload: AdminRolePayload) => void }) {
  const ref = useDialogAccessibility(true, onClose, !busy), lockedName = Boolean(role && systemRoles.has(role.name));
  const [name, setName] = useState(role?.name ?? ""), [selected, setSelected] = useState(role?.permissions ?? []), [error, setError] = useState("");
  const groups = useMemo(() => Object.entries(Object.groupBy(permissions, (permission) => permission.name.split(".")[0])), [permissions]);
  const toggleGroup = (names: string[], checked: boolean) => setSelected((current) => checked ? [...new Set([...current, ...names])] : current.filter((name) => !names.includes(name)));
  return <div ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-labelledby="role-dialog-title" className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form noValidate onSubmit={(event) => { event.preventDefault(); const normalized = name.trim().toLowerCase(); if (!/^[a-z0-9._-]+$/.test(normalized)) { setError("Tên role chỉ dùng chữ thường, số, dấu chấm, gạch dưới hoặc gạch ngang."); return; } onSubmit({ name: normalized, permissions: selected }); }} className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-md bg-white p-5 shadow-xl"><div className="flex justify-between"><div><h2 id="role-dialog-title" className="text-lg font-bold">{role ? `Vai trò ${role.name}` : "Tạo vai trò"}</h2><p className="mt-1 text-sm text-[#60727a]">Chọn các quyền backend sẽ enforce cho vai trò này.</p></div><button type="button" aria-label="Đóng" disabled={busy} onClick={onClose} className="size-8"><i className="fas fa-xmark" /></button></div><label className="mt-5 block text-sm font-semibold">Tên vai trò<input autoFocus={!lockedName} disabled={lockedName} maxLength={100} value={name} onChange={(e) => setName(e.target.value.toLowerCase().replace(/\s+/g, "-"))} className="mt-1 h-10 w-full rounded border border-[#cbd6d8] px-3 font-mono font-normal disabled:bg-[#eef2f2]" /></label>{error && <p role="alert" className="mt-2 text-sm text-red-700">{error}</p>}<div className="mt-5 space-y-4">{groups.map(([group, items]) => { const names = (items ?? []).map((item) => item.name), all = names.every((name) => selected.includes(name)); return <fieldset key={group} className="border-t border-[#dce3e5] pt-3"><legend className="flex w-full items-center justify-between text-sm font-bold uppercase"><span>{group}</span><label className="flex items-center gap-2 text-xs font-semibold normal-case"><input type="checkbox" checked={all} onChange={(e) => toggleGroup(names, e.target.checked)} className="size-4 accent-[#116966]" />Chọn nhóm</label></legend><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(items ?? []).map((permission) => <label key={permission.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(permission.name)} onChange={(e) => setSelected((current) => e.target.checked ? [...current, permission.name] : current.filter((name) => name !== permission.name))} className="size-4 accent-[#116966]" /><code>{permission.name}</code></label>)}</div></fieldset>; })}</div><div className="mt-6 flex justify-end gap-2"><button type="button" disabled={busy} onClick={onClose} className="rounded border border-[#cbd6d8] px-4 py-2 text-sm font-semibold">Hủy</button><button type="submit" disabled={busy || !name} className="rounded bg-[#116966] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Đang lưu..." : "Lưu vai trò"}</button></div></form></div>;
}

export default function AdminPermissionDirectory() {
  const [permissions, setPermissions] = useState<AdminPermissionResource[]>([]), [roles, setRoles] = useState<AdminRole[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null), [editing, setEditing] = useState<AdminRole | null | undefined>(undefined), [deleting, setDeleting] = useState<AdminRole | null>(null), [busy, setBusy] = useState(false), [reload, setReload] = useState(0);
  const load = useCallback(async (signal?: AbortSignal) => { const [nextPermissions, nextRoles] = await Promise.all([adminService.getPermissions(signal), adminService.getRoles(signal)]); setPermissions(nextPermissions); setRoles(nextRoles); }, []);
  useEffect(() => { const controller = new AbortController(); Promise.resolve().then(() => load(controller.signal)).catch((e) => { if (!axios.isCancel(e)) setError(normalizeApiError(e).message); }).finally(() => setLoading(false)); return () => controller.abort(); }, [load, reload]);
  const save = async (payload: AdminRolePayload) => { setBusy(true); try { if (editing) await adminService.updateRole(editing.id, systemRoles.has(editing.name) ? { permissions: payload.permissions } : payload); else await adminService.createRole(payload); toast.success(editing ? "Đã cập nhật vai trò." : "Đã tạo vai trò."); setEditing(undefined); await load(); } catch (e) { toast.error(normalizeApiError(e).message); } finally { setBusy(false); } };
  const remove = async () => { if (!deleting || busy) return; setBusy(true); try { await adminService.deleteRole(deleting.id); toast.success("Đã xóa vai trò."); setDeleting(null); await load(); } catch (e) { toast.error(normalizeApiError(e).message); setDeleting(null); await load(); } finally { setBusy(false); } };
  return <section><header className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-xl font-bold">Vai trò và quyền hạn</h1><p className="mt-1 text-sm text-[#60727a]">Phân quyền vận hành theo các policy backend.</p></div><button type="button" onClick={() => setEditing(null)} className="h-9 rounded bg-[#116966] px-4 text-sm font-semibold text-white"><i className="fas fa-plus mr-2" />Tạo vai trò</button></header>{loading ? <LoadingState label="Đang tải vai trò..." /> : error ? <ErrorState message={error} onRetry={() => { setError(null); setLoading(true); setReload((v) => v + 1); }} /> : <><AdminDataTable rows={roles} rowKey={(role) => role.id} columns={[{ key: "name", header: "Vai trò", render: (role) => <div><strong className="font-mono">{role.name}</strong>{systemRoles.has(role.name) && <span className="ml-2 text-xs text-[#60727a]">Hệ thống</span>}</div> }, { key: "permissions", header: "Quyền", render: (role) => <span>{role.permissions.length} quyền</span> }, { key: "users", header: "Người dùng", render: (role) => role.users_count }, { key: "actions", header: "Thao tác", render: (role) => <div className="flex"><button type="button" title="Chỉnh sửa quyền" aria-label={`Chỉnh sửa vai trò ${role.name}`} onClick={() => setEditing(role)} className="size-8 text-[#116966]"><i className="fas fa-pen" /></button>{!systemRoles.has(role.name) && <button type="button" title={role.users_count ? "Vai trò đang được sử dụng" : "Xóa"} aria-label={`Xóa vai trò ${role.name}`} disabled={role.users_count > 0} onClick={() => setDeleting(role)} className="size-8 text-red-700 disabled:text-[#a8b2b6]"><i className="fas fa-trash" /></button>}</div> }]} emptyMessage="Chưa có vai trò." /><p className="mt-3 text-xs text-[#60727a]">{permissions.length} quyền backend đang khả dụng.</p></>}{editing !== undefined && <RoleDialog role={editing} permissions={permissions} busy={busy} onClose={() => setEditing(undefined)} onSubmit={save} />}{deleting && <AdminConfirmDialog title="Xóa vai trò" message={`Xóa vai trò ${deleting.name}? Backend sẽ từ chối nếu vai trò đang được gán cho người dùng.`} confirmLabel="Xóa vai trò" destructive busy={busy} onClose={() => setDeleting(null)} onConfirm={remove} />}</section>;
}
